# docker stack deploy -c stack.yml jupyter
# optional pgadmin container
version: "3.7"
networks:
  demo-net:
services:
  spark:
    image: jupyter/all-spark-notebook:latest
    ports:
    - "8888:8888/tcp"
    - "4040:4040/tcp"
    - "7777:7777/tcp"
    networks:
    - demo-net
    working_dir: /home/$USER/work
    environment:
      CHOWN_HOME: "yes"
      GRANT_SUDO: "yes"
      NB_UID: 1000
      NB_GID: 100
      NB_USER: $USER
      NB_GROUP: staff
    user: root
    deploy:
     replicas: 1
     restart_policy:
       condition: on-failure
    volumes:
    - $PWD/work:/home/$USER/work
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: postgres
    ports:
    - "5432:5432/tcp"
    networks:
    - demo-net
    volumes:
    - $HOME/data/postgres:/var/lib/postgresql/data
    deploy:
     restart_policy:
       condition: on-failure
  postgres_backup:
    image: postgres:12-alpine
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: postgres
    ports:
    - "5431:5431/tcp"
    networks:
    - demo-net
    volumes:
    - $HOME/data/postgres_backup:/var/lib/postgresql/data
    deploy:
     restart_policy:
       condition: on-failure
  postgres_dwh:
    image: postgres:12-alpine
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: dati_finali
    ports:
    - "5430:5430/tcp"
    networks:
    - demo-net
    volumes:
    - $HOME/data/postgres_dwh:/var/lib/postgresql/data
    deploy:
     restart_policy:
       condition: on-failure
  # adminer:
  #   image: adminer:latest
  #   ports:
  #   - "8080:8080/tcp"
  #   networks:
  #   - demo-net
  #   deploy:
  #    restart_policy:
  #      condition: on-failure
  redis:
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    networks:
      - demo-net
    volumes:
      - $HOME/data/redis:/var/lib/redis
      #- $PWD/redis.conf:/usr/local/etc/redis/redis.conf
  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
      - postgres_backup
      - postgres_dwh
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: 5up3rS3cr3t!
    ports:
      - "8180:80/tcp"
    networks:
      - demo-net
    deploy:
      restart_policy:
        condition: on-failure
